In [1]:
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import GridSearchCV

In [2]:
X= pd.read_csv('/content/drive/MyDrive/All csv files/HAR HAPT/test_X.csv')
Y=pd.read_csv('/content/drive/MyDrive/All csv files/HAR HAPT/test_Y.csv')

In [3]:
#Import Module
from sklearn.model_selection import train_test_split


train_X, test_X, train_Y, test_Y = train_test_split(X, Y,
                                                    train_size=0.7,
                                                    test_size=0.3,
                                                    random_state=1)
print("Labels for training and testing data")
print(train_Y)
print(test_Y)

Labels for training and testing data
      Unnamed: 0  activity
2951        2951         2
635          635         3
720          720         4
254          254         1
2231        2231         6
...          ...       ...
2763        2763         5
905          905         1
1096        1096         3
235          235         6
1061        1061         1

[2213 rows x 2 columns]
      Unnamed: 0  activity
1468        1468         5
481          481         2
1934        1934         2
678          678         4
730          730         6
...          ...       ...
2903        2903         3
270          270         1
1938        1938         3
2767        2767         5
1301        1301         5

[949 rows x 2 columns]


In [4]:
df=pd.DataFrame(data=train_Y)
df1=pd.DataFrame(data=test_Y)
train_Y=df['activity']
test_Y=df1['activity']
duplicate=df[df.duplicated()]
print("Duplicated Row in train dataset",duplicate)
duplicate1=df1[df1.duplicated()]
print("Duplicated Row in test dataset",duplicate1)
print(train_X.shape)
print(test_X.shape)
print(train_Y.shape)
print(test_Y.shape)

Duplicated Row in train dataset Empty DataFrame
Columns: [Unnamed: 0, activity]
Index: []
Duplicated Row in test dataset Empty DataFrame
Columns: [Unnamed: 0, activity]
Index: []
(2213, 562)
(949, 562)
(2213,)
(949,)


In [5]:
df2=pd.DataFrame(data=train_X)
df3=pd.DataFrame(data=test_X)
print(df2.isna().sum())
print(df.isna().sum())
print(df1.isna().sum())
print(df3.isna().sum())

Unnamed: 0                         0
tBodyAcc-Mean-1                    0
tBodyAcc-Mean-2                    0
tBodyAcc-Mean-3                    0
tBodyAcc-STD-1                     0
                                  ..
tBodyGyro-AngleWRTGravity-1        0
tBodyGyroJerk-AngleWRTGravity-1    0
tXAxisAcc-AngleWRTGravity-1        0
tYAxisAcc-AngleWRTGravity-1        0
tZAxisAcc-AngleWRTGravity-1        0
Length: 562, dtype: int64
Unnamed: 0    0
activity      0
dtype: int64
Unnamed: 0    0
activity      0
dtype: int64
Unnamed: 0                         0
tBodyAcc-Mean-1                    0
tBodyAcc-Mean-2                    0
tBodyAcc-Mean-3                    0
tBodyAcc-STD-1                     0
                                  ..
tBodyGyro-AngleWRTGravity-1        0
tBodyGyroJerk-AngleWRTGravity-1    0
tXAxisAcc-AngleWRTGravity-1        0
tYAxisAcc-AngleWRTGravity-1        0
tZAxisAcc-AngleWRTGravity-1        0
Length: 562, dtype: int64


In [6]:
st=StandardScaler()
X_train=st.fit_transform(train_X)
X_test=st.transform(test_X)

In [7]:
rfc = RandomForestClassifier()
param_grid_rf = {'max_depth': list(range(5, 11)),'n_estimators':np.arange(3,15,2)}
grid_rf = GridSearchCV(rfc, param_grid_rf, n_jobs=-1)
grid_search_rf=grid_rf.fit(X_train, train_Y)

In [8]:
print("Best parameters for Random Forest:\n",grid_search_rf.best_params_)

Best parameters for Random Forest:
 {'max_depth': 10, 'n_estimators': 13}


In [9]:
classifier_rf = RandomForestClassifier(random_state=1, n_jobs=-1, max_depth=8,n_estimators=13,criterion='entropy',oob_score=True)
classifier_rf.fit(X_train, train_Y)
classifier_rf.oob_score_
Y_pred_rf=classifier_rf.predict(X_test)
print("Confusion Matrix:\n",confusion_matrix(test_Y, Y_pred_rf))
print("Accuracy of Random Forest:",accuracy_score(test_Y,Y_pred_rf))

Confusion Matrix:
 [[155   2   1   0   0   0   0   0   0   0   0   0]
 [  1 146   1   0   0   0   0   0   0   0   0   0]
 [  2   5 124   0   0   0   0   0   0   0   0   0]
 [  0   0   0 143  13   0   0   0   0   0   0   0]
 [  0   0   0   6 144   0   0   0   0   0   0   0]
 [  0   0   0   1   0 153   0   0   0   0   0   0]
 [  0   0   0   0   1   0   4   0   0   0   0   0]
 [  0   0   0   1   0   0   0   2   0   0   0   0]
 [  0   0   0   0   0   0   1   0  10   0   1   0]
 [  0   0   0   0   0   0   0   0   0   3   1   7]
 [  0   1   0   0   0   0   1   0   5   0   7   1]
 [  0   0   0   0   0   0   0   0   0   0   0   6]]
Accuracy of Random Forest: 0.9452054794520548


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


In [10]:
from sklearn.metrics import classification_report
print(classification_report(test_Y, Y_pred_rf))

              precision    recall  f1-score   support

           1       0.98      0.98      0.98       158
           2       0.95      0.99      0.97       148
           3       0.98      0.95      0.96       131
           4       0.95      0.92      0.93       156
           5       0.91      0.96      0.94       150
           6       1.00      0.99      1.00       154
           7       0.67      0.80      0.73         5
           8       1.00      0.67      0.80         3
           9       0.67      0.83      0.74        12
          10       1.00      0.27      0.43        11
          11       0.78      0.47      0.58        15
          12       0.43      1.00      0.60         6

    accuracy                           0.95       949
   macro avg       0.86      0.82      0.80       949
weighted avg       0.95      0.95      0.94       949

