In [1]:
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import GridSearchCV

In [2]:
X_train= pd.read_csv('/content/drive/MyDrive/All csv files/WISDM/5_ds_WISDM_first_phase_feature_train_1.csv')
Y_train = pd.read_csv('/content/drive/MyDrive/All csv files/WISDM/5_ds_WISDM_first_phase_label_train_1.csv')
X_test=pd.read_csv('/content/drive/MyDrive/All csv files/WISDM/5_ds_WISDM_first_phase_feature_test_1.csv')
Y_test=pd.read_csv('/content/drive/MyDrive/All csv files/WISDM/5_ds_WISDM_first_phase_label_test_1.csv')

In [3]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)
Y_test.head()

(14723, 1001)
(14723, 2)
(6310, 1001)
(6310, 2)


Unnamed: 0  activity
0       12309         2
1       14625         2
2        2127         0
3       12985         3
4       17273         3

In [4]:
df=pd.DataFrame(data=Y_train)
df1=pd.DataFrame(data=Y_test)
Y_train=df['activity']
Y_test=df1['activity']
duplicate=df[df.duplicated()]
print("Duplicated Row in train dataset",duplicate)
duplicate1=df1[df1.duplicated()]
print("Duplicated Row in test dataset",duplicate1)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

Duplicated Row in train dataset Empty DataFrame
Columns: [Unnamed: 0, activity]
Index: []
Duplicated Row in test dataset Empty DataFrame
Columns: [Unnamed: 0, activity]
Index: []
(14723, 1001)
(6310, 1001)
(14723,)
(6310,)


In [5]:
df2=pd.DataFrame(data=X_train)
df3=pd.DataFrame(data=X_test)
print(df2.isna().sum())
print(df.isna().sum())
print(df1.isna().sum())
print(df3.isna().sum())

Unnamed: 0    0
0             0
1             0
2             0
3             0
             ..
995           0
996           0
997           0
998           0
999           0
Length: 1001, dtype: int64
Unnamed: 0    0
activity      0
dtype: int64
Unnamed: 0    0
activity      0
dtype: int64
Unnamed: 0    0
0             0
1             0
2             0
3             0
             ..
995           0
996           0
997           0
998           0
999           0
Length: 1001, dtype: int64


In [6]:
st=StandardScaler()
X_train=st.fit_transform(X_train)
X_test=st.transform(X_test)

In [7]:
rfc = RandomForestClassifier()
param_grid_rf = {'max_depth': list(range(5, 11)),'n_estimators':np.arange(3,15,2)}
grid_rf = GridSearchCV(rfc, param_grid_rf, n_jobs=-1)
grid_search_rf=grid_rf.fit(X_train, Y_train)

In [8]:
print("Best parameters for Random Forest:\n",grid_search_rf.best_params_)

Best parameters for Random Forest:
 {'max_depth': 10, 'n_estimators': 11}


In [9]:
classifier_rf = RandomForestClassifier(random_state=1, n_jobs=-1, max_depth=8,n_estimators=13,criterion='entropy',oob_score=True)
classifier_rf.fit(X_train, Y_train)
classifier_rf.oob_score_
Y_pred_rf=classifier_rf.predict(X_test)
print("Confusion Matrix:\n",confusion_matrix(Y_test, Y_pred_rf))
print("Accuracy of Random Forest:",accuracy_score(Y_test,Y_pred_rf))

Confusion Matrix:
 [[ 280    0    1    0    6    0]
 [   8  328    0    0    4    0]
 [   0    0 2424    7   18    1]
 [   0    0   30 1898    5    0]
 [   2    0  353   61  261   17]
 [   0    0  396   35   77   98]]
Accuracy of Random Forest: 0.8381933438985737


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:583: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(


In [10]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred_rf))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97       287
           1       1.00      0.96      0.98       340
           2       0.76      0.99      0.86      2450
           3       0.95      0.98      0.96      1933
           4       0.70      0.38      0.49       694
           5       0.84      0.16      0.27       606

    accuracy                           0.84      6310
   macro avg       0.87      0.74      0.76      6310
weighted avg       0.84      0.84      0.81      6310

